### ISSUE TITLE
[ISSUE] Sonic Advance 2 fails to compile on Linux with GCC15.1.1

### ISSUE THREAD

**Issue by BlueSwordM** [SAT-R/sa2#212]
**Overview**
Building the project results in a failure due to some complaints from GCC15 about C standards.

**Branch**
In which branch does the issue appear to be occurring?
- [x] `main`

**Reproduction**
1. `git clone https://github.com/SAT-R/sa2 --depth 1`
2. `make sdl` with GCC15 as the compiler

**Expected behavior**
The project should build as expected.

**Platform (please complete the following information):**
 - Operating System: Fully up to date CachyOS Linux, 6.15.0 kernel
- Available compilers: GCC 15.1.1, Clang version 19.1.7
 - System information: Ryzen 9 5900X, 32GB of RAM, AMD Radeon VII GPU

**Additional context / Relevant Files**
Here is the error in question:
```C
make sdl
In file included from ArenaAlloc.c:24:
types.h:8:21: error: ‘bool’ cannot be defined via ‘typedef’
    8 | typedef signed char bool;
      |                     ^~~~
types.h:8:21: note: ‘bool’ is a keyword with ‘-std=c23’ onwards
types.h:8:1: warning: useless type name in empty declaration
    8 | typedef signed char bool;
      | ^~~~~~~
In file included from ArenaAlloc.c:24:
types.h:8:21: error: ‘bool’ cannot be defined via ‘typedef’
    8 | typedef signed char bool;
      |                     ^~~~
types.h:8:21: note: ‘bool’ is a keyword with ‘-std=c23’ onwards
types.h:8:1: warning: useless type name in empty declaration
    8 | typedef signed char bool;```

**Comment by freshollie** [comment]
I've pushed something which may fix it: https://github.com/SAT-R/sa2/commit/1a02bc7aeac9de9cc4995e1e2d7034f9b1efd63f
